# General-purpose Node image with pnpm available

ARG NODE_TAG=24-alpine
ARG PNPM_VERSION=10.27.0

FROM node:${NODE_TAG}

RUN apk add --no-cache git curl vim

RUN corepack enable pnpm && corepack install -g pnpm@${PNPM_VERSION}

ENV GIT_DIR=/find-a-friend/.git
ENV GIT_WORK_TREE=/find-a-friend

WORKDIR /find-a-friend