@baseUrl=http://localhost:3333

POST {{baseUrl}}/pets
Content-Type: application/json

{
  "org_id": "d6ff268f-4a24-431f-8914-146a84199d11",
  "name": "Thor",
  "description": "Friendly and playful dog, great with kids",
  "age": "ADULT",
  "size": "LARGE",
  "energy_level": "FOUR",
  "independence_level": "THREE",
  "additional_characteristics": "Vaccinated, neutered"
}
