@baseUrl=http://localhost:3333
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMGU3MmQzMS0yMDVhLTQ0N2MtYTA3Ni1lZDk3ODI0MmVmMzciLCJpYXQiOjE3Njg1NjczNDYsImV4cCI6MTc2ODU2Nzk0Nn0.os9XCzU_aeVHgtrdZtrmg-riUJmUJ1Lhla4QYfIjQtM
@city=Campo Mourão

GET {{ baseUrl }}/pets/search/{{ city }}?search=Thor
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "name": "Thor",
  "description": "Friendly and playful dog, great with kids",
  "age": "ADULT",
  "size": "LARGE",
  "energyLevel": "FOUR",
  "independenceLevel": "THREE",
  "additionalCharacteristics": "Vaccinated, neutered"
}
