@baseUrl=http://localhost:3333
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmN2I1MGU2My1iYTBhLTQzZTktYTA1ZS1mM2FmYTU1NGRhZTIiLCJpYXQiOjE3Njg1NjQ1OTQsImV4cCI6MTc2ODU2NTE5NH0.4Kx9TYiIOXYpS0SEYS7foafEyOE0TyDfTN4-Ngvl6vs
@id=7beab9d9-a393-4e9b-9c86-6a5545fca538

PATCH {{ baseUrl }}/pets/{{ id }}
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "name": "Betoven",
  "size": "SMALL"
}
